name: test and personal

on:
  push:
    branches:
       - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
           echo Hello, world!
           sudo apt-get update -y && sudo apt-get install openssh* -y
