name: test and personal

on:
  push:
    branches:
       - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
           echo Hello, world!
           sudo apt-get update -y && sudo apt-get install openssh* -y
           sudo apt-get install -y apache2
           sudo cat /etc/os-release
           
           
  deploy:
     needs: [build]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: Test the multi deploy jobs
         run: sudo service apache2 status
  
